#!/bin/bash -e

#©keithhedger Sun Jul 30 13:47:57 BST 2023 kdhedger68713@gmail.com

if [ "X$1" = "X" ];then
	exit 100
fi

if [ "X$2" = "X" ];then
	exit 100
fi

for arg in $2
	do
		cp -rv ${1} ${arg}x${arg}
		cd ${arg}x${arg}
		find -iname "*.png" | while read file
			do

				if [ ! -L "$file" ];then
					echo Converting "$file" ...
					mogrify -resize ${arg}x${arg} "$file"
				fi
			done
		cd -
	done

cat >index.theme<<EOF
[Icon Theme]
Name=Spring Wood Icons
Comment=A GNOME/Xfce4 icon theme created by Pedram Pourang (aka Tsu Jan), inspired by nuoveXT-1.6 and tweeked by K.D.Hedger kdhedger68713@gmail.com
Inherits=gnome

Directories=$(find -type d -mindepth 2 |sort -V|tr '\n' ','|sed 's@\./@@g')

EOF

while read
	do
		echo [$REPLY] >>index.theme
		echo Size=${REPLY%x?*} >>index.theme
		x=${REPLY#?*/}
		echo Context=${x^} >>index.theme
		if [ ${REPLY%x?*} -gt 48 ];then
			echo "Type=Scalable" >>index.theme
		else
			echo "Type=Fixed" >>index.theme
		fi
		echo >>index.theme
	done< <(find -type d -mindepth 2 |sort -V|sed 's@\./@@g')
