#!/bin/bash

#©keithhedger Fri 18 Mar 13:02:28 GMT 2022 kdhedger68713@gmail.com

ln -sv ../stock/stock_apply.png actions/dialog-ok.png
ln -sv ../stock/stock_about.png actions/help-about.png
ln -sv ../stock/stock_new.png actions/document-new.png
ln -sv ../stock/stock_print.png actions/document-print.png
ln -sv ../stock/stock_save.png actions/document-save.png
ln -sv ../stock/stock_save-as.png actions/document-save-as.png
ln -sv ../stock/stock_clear.png actions/edit-clear.png
ln -sv ../stock/stock_copy.png actions/edit-copy.png
ln -sv ../stock/stock_cut.png actions/edit-cut.png
ln -sv ../stock/stock_delete.png actions/edit-delete.png
ln -sv ../stock/stock_find.png actions/edit-find.png
ln -sv ../stock/stock_find-and-replace.png actions/edit-find-replace.png
ln -sv ../stock/stock_paste.png actions/edit-paste.png
ln -sv ../stock/stock_redo.png actions/edit-redo.png
ln -sv ../stock/stock_undo.png actions/edit-undo.png
ln -sv ../stock/stock_goto-bottom.png actions/go-bottom.png
ln -sv ../stock/stock_go-down.png actions/go-down.png
ln -sv ../stock/stock_goto-first.png actions/go-first.png
ln -sv ../stock/stock_home.png actions/go-home.png
ln -sv ../stock/stock_jump-to.png actions/go-jump.png
ln -sv ../stock/stock_goto-last.png actions/go-last.png
ln -sv ../stock/stock_go-forward.png actions/go-next.png
ln -sv ../stock/stock_go-back.png actions/go-previous.png
ln -sv ../stock/stock_goto-top.png actions/go-top.png
ln -sv ../stock/stock_go-up.png actions/go-up.png
ln -sv ../stock/stock_help.png actions/help-contents.png
ln -sv ../stock/stock_dialog_question.png actions/dialog-question.png
ln -sv ../stock/stock_dialog_warning.png actions/dialog-warning.png
ln -sv ../stock/stock_close.png actions/window-close.png
ln -sv ../stock/stock_sort-ascending.png actions/view-sort-ascending.png
ln -sv ../stock/stock_sort-descending.png actions/view-sort-descending.png
ln -sv ../stock/stock_add.png actions/list-add.png
ln -sv ../stock/stock_preferences.png actions/preferences-desktop.png
ln -sv ../stock/stock_run.png actions/system-run.png
ln -sv ../stock/stock_new.png actions/window-new.png
ln -sv ../stock/stock_new.png actions/open-in-new-tab.png
ln -sv ../apps/evolution.png actions/mail-send.png
ln -sv ../apps/evolution.png actions/mail-message-new.png


ln -sv ../stock/stock_zoom-fit.png actions/zoom-fit-best.png
ln -sv ../stock/stock_zoom-in.png actions/zoom-in.png
ln -sv ../stock/stock_zoom-out.png actions/zoom-out.png
ln -sv ../stock/stock_zoom-100.png actions/zoom-original.png
ln -sv ../stock/stock_zoom-100.png actions/zoom.png

ln -sv ../apps/accessories-text-editor.png actions/accessories-text-editor.png
ln -sv ../apps/accessories-text-editor.png actions/accessories-text-editor.png
ln -sv ../apps/accessories-text-editor.png actions/gtk-edit.png

ln -sv ../stock/stock_preferences.png actions/preferences-system.png
ln -sv ../stock/stock_preferences.png actions/gtk-preferences.png

ln -sv ../stock/stock_refresh.png actions/view-refresh

ln -sv ../stock/stock_refresh.png actions/view-refresh.png
ln -sv ../stock/stock_stop.png actions/process-stop.png

ln -sv ../stock/stock_spell-check.png actions/tools-check-spelling.png
ln -sv ../stock/stock_remove.png actions/list-remove.png

ln -sv ../stock/stock_cancel.png actions/cancel.png
ln -sv ../stock/stock_cancel.png actions/dialog-cancel.png
ln -sv ../stock/stock_cancel.png actions/gtk-cancel.png

ln -sv ../stock/stock_cancel.png actions/gtk-no.png
ln -sv ../stock/stock_cancel.png actions/close.png
ln -sv ../stock/stock_cancel.png actions/stop.png
ln -sv ../stock/stock_cancel.png actions/gtk-stop.png
ln -sv ../stock/stock_cancel.png actions/gtk-quit.png

ln -sv ../stock/stock_cancel.png actions/dialog-close.png
ln -sv ../stock/stock_cancel.png actions/gtk-close.png
ln -sv ../stock/stock_apply.png actions/gtk-yes.png

ln -sv ../stock/stock_apply.png actions/gtk-ok.png


